<?php
#
# File generated by Dolibarr installer 3.0.1 on 2011-11-17 01:15:28
#
# Take a look at conf.php.example file for an example of conf.php file
# and explanations for all possibles parameters.
#
$dolibarr_main_url_root='http://protocall.fr/dolibarr';
$dolibarr_main_document_root='/home/httpd/vhosts/protocall.fr/httpdocs/dolibarr';
#$dolibarr_main_url_root_alt='http://protocall.fr/dolibarr/custom';
#$dolibarr_main_document_root_alt='/home/httpd/vhosts/protocall.fr/httpdocs/dolibarr/custom';
$dolibarr_main_data_root='/home/httpd/vhosts/protocall.fr/httpdocs/dolibarr/documents';
$dolibarr_main_db_host='localhost';
$dolibarr_main_db_port='';
$dolibarr_main_db_name='protocall02';
$dolibarr_main_db_user='protocall_PGM';
$dolibarr_main_db_pass='ixs8Q39kozgE';
$dolibarr_main_db_type='mysqli';
$dolibarr_main_db_character_set='utf8';
$dolibarr_main_db_collation='utf8_general_ci';
$dolibarr_main_authentication='dolibarr';

# Specific settings
$dolibarr_main_prod='0';
$dolibarr_nocsrfcheck='0';
$dolibarr_main_force_https='0';
$dolibarr_main_cookie_cryptkey='f3842611835c8d0ac1d6144e6d94de8d';
$dolibarr_mailing_limit_sendbyweb='10';
?>